version: '3'

services:

    puppet:
        image: puppet/puppetserver-standalone
        expose: 
            - 8140
        hostname: puppet
        volumes: 
            - ./code:/etc/puppetlabs/code/
        
    puppetnode:
        image: puppet/puppet-agent
        links: 
            - puppet:puppet
       
